### ISSUE TITLE
HELP！Failed to download geoip database. Check your Internet connection.

### ISSUE THREAD

**Issue by 404nofound** [leolewis/openvisualtraceroute#12]
Hi there,

Please check it in version 2.0.0.
It seems like the SSL certification problem.

Thanks

Eddy

**Comment by 404nofound** [comment]
![1641198430(1)](https://user-images.githubusercontent.com/43553114/147911224-6397497c-58eb-454c-b8c8-651349039693.png)

**Comment by leolewis** [comment]
Can you please attach the logs under $USER_HOME/ovtr/ovtr.log?

**Comment by 404nofound** [comment]
2022-01-04 15:39:56,521 INFO [main] o.l.t.Main:55 Open Visual Traceroute 2.0.0 
2022-01-04 15:39:56,547 INFO [main] o.l.t.i.Env:287 Java run-time version: 17.0.1
2022-01-04 15:39:56,548 INFO [main] o.l.t.i.Env:288 NASA WorldWind Java v2.2.0
2022-01-04 15:39:56,548 INFO [main] o.l.t.i.Env:289 Library Path C:\Program Files\Java\jdk-17.0.1\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;E:\matlab\bin;E:\go\bin;C:\ProgramData\chocolatey\bin;E:\nodejs\node_global\;E:\nodejs\;F:\Git\cmd;C:\Tesseract-OCR;D:\python3\Scripts\;D:\python3\;C:\Users\Eddy\AppData\Local\Microsoft\WindowsApps;C:\Users\Eddy\go\bin;C:\Users\Eddy\AppData\Roaming\npm;C:\Program Files\Java\jdk-17.0.1\bin;.
2022-01-04 15:39:56,554 INFO [main] o.l.t.i.Env:336 OS:Windows 10 / arch:amd64
2022-01-04 15:39:57,108 ERROR [SwingWorker-pool-1-thread-1] o.l.t.i.Env:903 Failed to download dynamic config. Fallback to default
java.net.UnknownHostException: raw.githubusercontent.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:246) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:351) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:373) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1276) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[na:na]
	at org.leo.traceroute.util.Util.followRedirectOpenConnection(Util.java:409) ~[org.leo.traceroute.jar:na]
	at org.leo.traceroute.install.Env.loadDynamicConf(Env.java:887) ~[org.leo.traceroute.jar:na]
	at org.leo.traceroute.Main$1.doInBackground(Main.java:123) ~[org.leo.traceroute.jar:na]
	at org.leo.traceroute.Main$1.doInBackground(Main.java:120) ~[org.leo.traceroute.jar:na]
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
2022-01-04 15:39:57,189 INFO [SwingWorker-pool-1-thread-1] o.l.t.c.g.GeoService:105 **Use geoip db C:\Users\Eddy\ovtr\GeoLite2-City.mmdb which is 18996 day(s) old**
2022-01-04 15:39:57,191 INFO [SwingWorker-pool-1-thread-1] o.l.t.c.g.GeoService:112 **Downloading GeoIP database to C:\Users\Eddy\ovtr\GeoLite2-City.mmdb...**
2022-01-04 15:39:57,975 ERROR [AWT-EventQueue-0] o.l.t.Main:136 **Error while starting the application**
java.util.concurrent.ExecutionException: java.io.IOException: **Failed to download geoip database. Check your Internet connection.**
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na]
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613) ~[na:na]
	at org.leo.traceroute.Main$1.done(Main.java:131) ~[org.leo.traceroute.jar:na]
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750) ~[na:na]
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848) ~[na:na]
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112) ~[na:na]
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858) ~[na:na]
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311) ~[na:na]
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243) ~[na:na]
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) ~[na:na]
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191) ~[na:na]
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236) ~[na:na]
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318) ~[na:na]
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234) ~[na:na]
	at java.desktop/java.awt.Dialog.show(Dialog.java:1080) ~[na:na]
	at java.desktop/java.awt.Component.show(Component.java:1728) ~[na:na]
	at java.desktop/java.awt.Component.setVisible(Component.java:1675) ~[na:na]
	at java.desktop/java.awt.Window.setVisible(Window.java:1036) ~[na:na]
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1016) ~[na:na]
	at org.leo.traceroute.Main.lambda$main$1(Main.java:110) ~[org.leo.traceroute.jar:na]
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) ~[na:na]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) ~[na:na]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[na:na]
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[na:na]
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[na:na]
Caused by: java.io.IOException: Failed to download geoip database. Check your Internet connection.
	at org.leo.traceroute.core.geo.GeoService.doInit(GeoService.java:134) ~[org.leo.traceroute.jar:na]
	at org.leo.traceroute.core.geo.GeoService.init(GeoService.java:90) ~[org.leo.traceroute.jar:na]
	at org.leo.traceroute.core.ServiceFactory.init(ServiceFactory.java:96) ~[org.leo.traceroute.jar:na]
	at org.leo.traceroute.Main$1.doInBackground(Main.java:124) ~[org.leo.traceroute.jar:na]
	at org.leo.traceroute.Main$1.doInBackground(Main.java:120) ~[org.leo.traceroute.jar:na]
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.net.UnknownHostException: raw.githubusercontent.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:294) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[na:na]
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[na:na]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1276) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[na:na]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2887) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2796) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1927) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[na:na]
	at org.leo.traceroute.util.Util.followRedirectOpenConnection(Util.java:415) ~[org.leo.traceroute.jar:na]
	at org.leo.traceroute.core.geo.GeoService.doInit(GeoService.java:114) ~[org.leo.traceroute.jar:na]
	... 10 common frames omitted
2022-01-04 15:40:06,404 INFO [Shutdown] o.l.t.u.TraceRouteFrame:94 Application exited.

**Comment by leolewis** [comment]
Thanks that's very helpful. It looks like your ISP or network administrator is blocking access to github, which might happening to a few people. Can you check if you can download this file https://openvisualtraceroute.s3.amazonaws.com/GeoLite2City.tar.gz ?

**Comment by leolewis** [comment]
I also just uploaded a new build which will download the geoIP database from AWS S3 in case github cannot be accessed. If you want to git it a try, reinstall the latest from https://sourceforge.net/projects/openvisualtrace/files/2.0.0/ and see if it helps.

**Comment by 404nofound** [comment]
Great，It works！it's really a nice tool.

thanks for help and having a good day!
