### ISSUE TITLE
traceroute not work in Linux

### ISSUE THREAD

**Issue by kpf61** [leolewis/openvisualtraceroute#21]
![image](https://user-images.githubusercontent.com/130795902/232144666-fadfa760-5082-4b29-b812-57402473178b.png)
Error as shown

**Comment by GencoreOperative** [comment]
I get the same issue.
```
java.io.IOException: traceroute: invalid option -- 'n'
Try 'traceroute --help' or 'traceroute --usage' for more information.

	at org.leo.traceroute.core.route.impl.OSTraceRoute.computeRoute(OSTraceRoute.java:167) ~[org.leo.traceroute.jar:na]
	at org.leo.traceroute.core.route.impl.AbstractTraceRoute.lambda$compute$6(AbstractTraceRoute.java:190) ~[org.leo.traceroute.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```
For reference, I'm on Linux and using GNU inetutils:
```
$ traceroute -V
traceroute (GNU inetutils) 1.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Elian Gidoni.
```

**Comment by GencoreOperative** [comment]
To resolve this issue, you will need to install version `1.2.x` of traceroute rather than version `2.1.x`.

```
sudo apt install inetutils-traceroute  # version 2:1.9.4-11ubuntu0.1, or
sudo apt install traceroute            # version 1:2.1.0-2
```
Remove the `inetutils-traceroute` package and install the `traceroute`. This version has the `-n` flag the application is looking for.

**Comment by kpf61** [comment]
sorted
*Kindest Regards*
*Kevin*

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
15/05/23,
00:30:58
